# Generated by Django 4.2.2 on 2023-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_platform', '0002_music_uploads_model_protected_accessors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protected_accessors',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
