# Generated by Django 4.2.2 on 2023-06-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_platform', '0003_alter_protected_accessors_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protected_accessors',
            name='music_id',
        ),
        migrations.DeleteModel(
            name='music_uploads_model',
        ),
        migrations.DeleteModel(
            name='protected_accessors',
        ),
    ]
