# Generated by Django 4.2.2 on 2023-06-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_platform', '0007_alter_music_uploads_model_owner_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='protected_accessors',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='protected_accessors',
            name='music_id',
        ),
        migrations.DeleteModel(
            name='music_uploads_model',
        ),
        migrations.DeleteModel(
            name='protected_accessors',
        ),
    ]
