# Generated by Django 4.2.2 on 2023-06-16 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_platform', '0009_music_uploads_model_protected_accessors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protected_accessors',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
